language: node_js
node_js:
  - "stable"
cache: npm

before_install:
 - chmod +x ./frontend/todo-app/node_modules/.bin/react-scripts
 - rm ./frontend/todo-app/package-lock.json
 - rm -r ./frontend/todo-app/node_modules

install:
  - npm install
  - npm install react-scripts

before_script: cd ./frontend/todo-app/

script:
  - npm test
  - npm run build

deploy:
  - provider: pages
  - skip-cleanup: true
  - on:
      branch: frontend-test
      