language: node_js
# node_js:
cache:
  directories:
      - ./frontend/todo-app/node_modules

before_script:
 - cd ./frontend/todo-app/
 - chmod +x ./node_modules/.bin/react-scripts
#  - rm ./package-lock.json
#  - rm -r ./node_modules

# install:
#   - npm install
#   - npm install react-scripts

# before_script: cd ./frontend/todo-app/

script:
  - npm run build
  - npm test

# deploy:
#   - provider: pages
#   - skip-cleanup: true
#   - on:
#       branch: frontend-test
      