language: node_js
node_js:
  - "stable"
cache: npm

install:
  - npm install

before_script: cd ./frontend/todo-app/

script:
  - npm test

deploy:
  - provider: pages
  - skip-cleanup: true
  - on:
      branch: frontend-test