language: node_js
node_js:
  - "stable"
cache: npm
  directories:
  - node_modules

install:
  - npm install

before_script: cd ./frontend/todo-app/

script:
  - npm test
  - npm run test:coverage
  - npm run build

deploy:
  - provider: pages
  - skip-cleanup: true
  - github_token: $github_token
  - on:
      branch: frontend-test